routingPanier:
    resource: "@EcommerceBundle/Resources/config/routing/routingPanier.yml"
    prefix: /panier

routingProduits:
    resource: "@EcommerceBundle/Resources/config/routing/routingProduits.yml"
    prefix: /

routingProduitsAdmin:
    resource: "@EcommerceBundle/Resources/config/routing/routingProduitsAdmin.yml"
    prefix: /admin/produits

RoutingCategoriesAdmin:
    resource: "@EcommerceBundle/Resources/config/routing/routingCategoriesAdmin.yml"
    prefix:   /admin/categories

routingCommandes:
    resource: "@EcommerceBundle/Resources/config/routing/routingCommandes.yml"
    prefix: /commandes

RoutingCommandesAdmin:
    resource: "@EcommerceBundle/Resources/config/routing/routingCommandesAdmin.yml"
    prefix:   /admin/commandes