services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Ecommerce\EcommerceBundle\Services\GetReference:
        public: true

    Ecommerce\EcommerceBundle\Controller\ProduitsAdminController:
        tags: ['controller.service_arguments']

    Ecommerce\EcommerceBundle\Twig\Extension\:
        resource: '../../Twig/Extension/*'

    redirectionListener:
        class: Ecommerce\EcommerceBundle\Listener\RedirectionListener
        arguments:
            - '@service_container'
            - '@session'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    Ecommerce\EcommerceBundle\Services\FileUploader:
        public: true
        arguments:
            $targetDir: '%picture_directory%'


    Ecommerce\EcommerceBundle\Listener\PictureUploadListener:
        arguments:
            $targetDir: '%picture_directory%'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }